version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: olsap.6699
      POSTGRES_DB: grpc-golang
    ports:
      - "5433:5432"
    restart: unless-stopped
    
  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    ports:
      - "27024:27017"
    restart: unless-stopped

  app:
    build: .
    container_name: grpc_app
    network_mode: host
    ports:
     - "8081:8080"
    depends_on:
      - postgres
